//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escape_Math.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EscapeMathEntities3 : DbContext
    {
        public EscapeMathEntities3()
            : base("name=EscapeMathEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCategoria> tCategoria { get; set; }
        public virtual DbSet<tDetalleVenta> tDetalleVenta { get; set; }
        public virtual DbSet<tPost> tPost { get; set; }
        public virtual DbSet<tRangos> tRangos { get; set; }
        public virtual DbSet<tTarjeta> tTarjeta { get; set; }
        public virtual DbSet<tUsuarios> tUsuarios { get; set; }
        public virtual DbSet<tVenta> tVenta { get; set; }
    }
}
