//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escape_Math.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalleVenta
    {
        public long idDetalleVenta { get; set; }
        public long idventa { get; set; }
        public int idrangos { get; set; }
        public long catidad { get; set; }
    
        public virtual tVenta tVenta { get; set; }
        public virtual tRangos tRangos { get; set; }
    }
}
