//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escape_Math.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTarjeta
    {
        public long idTarjeta { get; set; }
        public int Ccv_tarjeta { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public int idCliente { get; set; }
    
        public virtual tUsuarios tUsuarios { get; set; }
    }
}
